"""
Description: this file define some basic constant variables for the game
Date: 2022-04-11 10:34:14
LastEditTime: 2022-04-13 20:34:19
"""
# the board size definitions
BOARD_HEIGHT = 8
BOARD_WIDTH = 5
# the chessman number definitions
SPACE_NUMBER = 0

# game result definitions
GAME_END_ODD_WIN = 1
GAME_END_EVEN_WIN = 2
GAME_END_DRAW = 0
GAME_STILL_PLAYING = 3

GAME_AI_MOVE = 2
GAME_HUMAN_MOVE = 1
GAME_NO_ONE_MOVE = 0

# visualization constants
# FPS
FPS = 15
# layout sizes

WINDOW_PLOT_VIEW_HEIGHT = 150
WINDOW_PLOT_VIEW_WIDTH = 480

WINDOW_HEIGHT = 480 + WINDOW_PLOT_VIEW_HEIGHT
WINDOW_WIDTH = 1080

WINDOW_BUTTON_HEIGHT = 40
WINDOW_BUTTON_WIDTH = 80

WINDOW_BUTTON_TEXT_SIZE = 20

WINDOW_CHESSBOARD_SIZE = 480

# layout positions
WINDOW_LEFT_PADDING = 20
WINDOW_TOP_PADDING = 20

WINDOW_LEFT_EDGE = WINDOW_CHESSBOARD_SIZE + WINDOW_LEFT_PADDING + 20
WINDOW_RIGHT_EDGE = 540

WINDOW_CHESSBOARD_X = WINDOW_LEFT_PADDING
WINDOW_CHESSBOARD_Y = WINDOW_TOP_PADDING

WINDOW_PLOT_VIEW_X = WINDOW_RIGHT_EDGE
WINDOW_PLOT_VIEW_Y = WINDOW_TOP_PADDING

WINDOW_STATUS_BOARD_Y = WINDOW_CHESSBOARD_Y+ WINDOW_CHESSBOARD_SIZE+20

# view object sizes
CHESSMAN_SIZE = 10
GRID_SIZE = 30
PADDING_RATIO = 1  # the ratio of padding between grid and board boundary of chessboard view
GRID_WIDTH = 1  # the width of the grid lines

PLOT_VIEW_PADDING = 10
# colors
WINDOW_BG_COLOR = (127, 127, 127)
WINDOW_TEXT_COLOR = (0, 0, 0)

WINDOW_BUTTON_AVAILABLE_COLOR = (0, 255, 0)
WINDOW_BUTTON_UNAVAILABLE_COLOR = (255, 0, 0)

WINDOW_PLOT_COLOR = (255, 255, 255)
# the chessman button color
FILL_COLOR_ODD = (0, 0, 0)
FILL_COLOR_EVEN = (255, 255, 255)
FILL_COLOR_ODD_TO_SELECT = (0, 0, 0, 50)
FILL_COLOR_EVEN_TO_SELECT = (255, 255, 255, 50)

# colors in chessboard
GRID_COLOR = (0, 0, 0)
CHESSBOARD_BG_COLOR = (188, 176, 71)

# view control constants
BUTTON_STATE_DEFAULT = 0
BUTTON_STATE_ON_TOUCH = 1
